### ISSUE TITLE
bootRun hangs

### ISSUE THREAD

**Issue by devAtx** [borysn/spring-boot-angular2#11]
Hello there,

i have a little issue:

always hang at :bootRun 88%. The application is running fine.

`myuser$ gradle bootrun
Building 88% > :bootRun`

My System:
`Darwin XXX 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64`

Java:
`java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)`

I can send you a full output from the gradle bootRun command if you need it.

Btw where is the right place to ask a question about the configuration for angular2? I like to add a new client lib and can't figure out how.

Thanks for your help.

**Comment by borysn** [comment]
What version of gradle are you using? And yeah, might as well post full log just in case. As far as adding a client lib, it's going to change slightly coming up, but  for now take a look at the [front-end dev](https://github.com/borysn/spring-boot-angular2/wiki/front-end-dev#adding-front-end-dependencies) wikie page @devAtx

**Comment by borysn** [comment]
@devAtx if you got everything going, I'd like to go ahead and close out the issue. If not, then that's ok, just lemmeh know what's good!
