### ISSUE TITLE
Doesn't work with FF and IE

### ISSUE THREAD

**Issue by szvini** [borysn/spring-boot-angular2#12]
I've tried to open the project in FireFox and IE. But I've got exception during the page loading.

Error: @http://localhost:8080/app/main.js:5:25
	@http://localhost:8080/app/main.js:1:1
	@http://localhost:8080/app/main.js:1:1
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:8080/js/lib/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:8080/js/lib/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:8080/js/lib/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:8080/js/lib/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:8080/js/lib/zone.js:256:29
	drainMicroTaskQueue@http://localhost:8080/js/lib/zone.js:474:26
	ZoneTask/this.invoke@http://localhost:8080/js/lib/zone.js:426:22
	
	Evaluating http://localhost:8080/app/app.component.js
	Evaluating http://localhost:8080/app/main.js
	Error loading http://localhost:8080/app/main.js
http://localhost:8080/js/lib/system.src.js
Line 123

**Comment by borysn** [comment]
@szvini for the sake of the future I recommend not using IE, imho. I'm surprised it's not running for you in FF, do you have the latest? I do not experience the same issue. Try running a `$ gradle clean assemble check bootRun --info`, and make sure any cache in your browser is cleaned out. I have my browser set to auto clean cache on refresh when the console tools are open.

**Comment by szvini** [comment]
Indeed, my FF version hasn't been up to date, I used 43.x.x version instead of 46.
Although I checked my FF version before using your project, and but it seems that only one update was not enough, because my FF was too old and I had to update again.

**Comment by borysn** [comment]
@szvini happy to hear it's working. this project is relatively bleeding-edge. Some of the packages are upgraded beyond what angular.io recommends for their starter project, and others are still in beta. Some of the recommendations I did take from angular.io are relatively new as well, like systemjs (no 1.0.0 release). This project also compiles ts to js es6, angular.io is recommending es5 still. Honestly I can't wait for full es7 support, and I hope the es5-es7 progression doesn't turn into a minefield

I suspect browser support will increase over time, how much will depend on what library. Some of the js dependencies in this project are also interchangeable with other js libraries. Imho, it's better to make a push forward towards a better future for web dev, and even in some cases eliminate browser support to do so.

This is all related to my deciding whether to battle out webpack config, or start hoping onto jspm as it evolves. If there are no more related problems, you can close the issue please (: or i'll get to it later on.

cheers!
