### ISSUE TITLE
Tentative date for new build setup

### ISSUE THREAD

**Issue by tapas4java** [borysn/spring-boot-angular2#13]
Hi,

Thanks for this starter repo. From the README, it seems you are working on few optimisations regarding build. I am going to start a new Angular2 and Spring project soon. Can you please provide any tentative date for completing those features(webpack etc) or I can access your WIP code base somewhere??

**Comment by borysn** [comment]
@tapas4java I apologize, but due to some foreseen circumstances I will not be able to set a tentative date. I'm trying to get to that asap, but things have gone a bit fubar. Atm, there is no WIP. I'd greatly appreciate community initiative for help. I'm also strongly considering migrating away from ts to dart, due to more issues from the ts community. It's been a rough ride. I'm hanging tight, but no promises. Again, my apologies.

**Comment by borysn** [comment]
@tapas4java I should clarify, the fubar issues are with my own life, not the project itself (kind of an exaggeration of my circumstance, nothing to really worry about) >.<

**Comment by borysn** [comment]
@tapas4java it's really not going to be that much more work, and I'm looking forward to it. Even with a migration to dart, it should be less than a week's worth of mild work. It's just getting to it with everything else going on. Aye. I have a decent tentative plan for everything, so far only logged in my head. I've been keeping up with a lot of the webpack and migration guides online. More and more pop up every week.

**Comment by borysn** [comment]
@tapas4java feel free to ask anymore questions, and if I could assist you in any other way, just let know. I'll do what I can.

**Comment by tapas4java** [comment]
@borysn, Thanks for your prompt reply. I feel moving to Dart from Typescript is not a good idea. Can I know the issues you came across with Typescript so far??

For client side scafolding, if we can integrate angular-cli directly, then it should minimize the maintaince overhead. Have you considered this?

**Comment by borysn** [comment]
@tapas4java the issues are genearlly from the community rather than with the language itself. I rather enjoy ts. 

I have not considered angular-cli, but I shall look into it! Thanks for the suggestion.

**Comment by anthonyikeda** [comment]
I wouldn't drop Typescript: there's been too much work to ensure its the primary language (I like Dart but there is more support for TS)

My question to some of the other commenters here, why do you want an integrated build solution?

**Comment by borysn** [comment]
Don't really see a reason to implement angular-cli, unless anyone has anything concrete to contribute to the issues raised, I'm going to go ahead and close the issue.

**Comment by borysn** [comment]
@anthony

**Comment by borysn** [comment]
@anthonyikeda not really sure support us greater than a good community, it's debatable for sure, but I'll always take a better community vs support.
