### ISSUE TITLE
not working like before .. error on home page

### ISSUE THREAD

**Issue by siddigd** [borysn/spring-boot-angular2#14]
Hi

After upgrade to rc6 and dividing code ... it is showing :+1: 
Whitelabel Error Page 

on 127.0.0.1:8080 - for both gradle bootRun and gradle bootRepackage and running Jar file

**Comment by borysn** [comment]
navigate to `localhost:3000`, angular code is served on it's own webpack dev server now. The rest api runs on tomcat which is at `localhost:8080`, there is no html content served from that port any longer. You can check the updated readme/wiki for more info.

**Comment by siddigd** [comment]
Hi

Many thanks for your reply. I thought the idea is to host the ui in spring as a frontend to access other remote rest, now no connection between rest client - ui - and jave code right ??
Regards

**Comment by borysn** [comment]
The idea is to have an app server abstracted away from a client. The app server can then be used for any front end client, like an android apps! 

The project then specifically focuses on a web client implementation using angular2. The only connection between the java code (app server) and the front end client (angular2) is the rest api, that was true before as well. 

The app server and the client can still access what ever rest api they need. The application functions the same, the web code is just served on it's own server following good restful methodology.

**Comment by siddigd** [comment]
Thanks a lot

**Comment by borysn** [comment]
@siddigd no problem!
