### ISSUE TITLE
single-server branch is broken

### ISSUE THREAD

**Issue by dragospd** [borysn/spring-boot-angular2#16]
Hi, I tried to execute the single-server project and the main page is broken (http://localhost:8080/js/lib/ng2-bootstrap.js Failed to load resource: the server responded with a status of 404 ())

**Comment by borysn** [comment]
@dragospd thanks for bringing that to my attention. Had to adjust for the new umd setup. You can go ahead and pull the changes.

**Comment by dragospd** [comment]
It's OK now, thanks.
