### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by danmwall** [borysn/spring-boot-angular2#19]
Is there any way you can commit an updated version of this project?  I have been trying to get a basic Angular2/Spring Boot/Gradle project working for a week now.  This one is very close to working, but there are some old versions of things in the package.json file and some deprecated functions.  I am doing my best to work through them, but I have never worked with these technologies before.

**Comment by borysn** [comment]
@danmwall i'm in the process of updating, unfortunately due to my absence things are taking a little longer than expected. i'll be looking into this soon. thanks for being patient.

**Comment by Manningham** [comment]
In nearly the same boat as @danmwall , just started setting things up this morning and am new to these technologies... will post if I run into issues and circumvent

**Comment by borysn** [comment]
@Manningham roger that. I got caught up in another project recently as i'm getting back into the upswing of everything. Update is still coming

**Comment by Manningham** [comment]
@borysn No rush, thanks!

**Comment by borysn** [comment]
@danmwall @Manningham updates are complete. I'll close out this issue. let me know if you guys have anymore trouble!

**Comment by Manningham** [comment]
Thanks @borysn , looking forward to playing with this Sunday!
