### ISSUE TITLE
Integrate bower dependency

### ISSUE THREAD

**Issue by cridmann** [borysn/spring-boot-angular2#23]
Hello,

First of all, thanks for the nice template!

I'm wanting to use this template if possible, but I'm struggling to incorporate a bower dependency into the webpack2 config.  Am I right in my understanding that the gradle-node plugin cannot be used for this, and thus I would need to include something like https://github.com/craigburke/client-dependencies-gradle ?

I added `frontend/bower.json`, and changed my `webpack.common.js` to use

```
    resolve: {
        modules: [helpers.root('src'), "node_modules", "bower_components"],
        descriptionFiles: ['bower.json', 'package.json'],
        extensions: ['.js', '.ts', '.css', '.scss', '.json', '.html']
    },
```

The gradle-node plugin of course does not install the bower_components, thus I have to manually `bower install`

Even when I do so, I can't figure out how to include a downloaded bower dependency in the actual code.  I'll keep trying and will update any findings.

**Comment by borysn** [comment]
@cridmann you can try one of these two options for installing automatically
1. just call bower from within scripts sections of the package.json for npm. please refer to the `postinstall` section of the [npm scripts doc](https://docs.npmjs.com/misc/scripts)
1. you can try an npm package called [bower-installer](https://www.npmjs.com/package/bower-installer)

as far as incorporating bower with webpack, please refer to the usage with bower [webpack doc](https://webpack.github.io/docs/usage-with-bower.html)

**Comment by cridmann** [comment]
@borysn - the first solution ended up working well.

As far as bower + webpack, I did see that doc, but it seems things changed when they upgraded to webpack2.  See: https://github.com/lpiepiora/bower-webpack-plugin/issues/39.  Anyways, I think my solution that I pasted in my original comment was actually working.  However, the complication is that the bower dependencies are also polymer web components, so there are additional configs you need to provide webpack for it to work.  I'm currently looking into https://github.com/aruntk/wc-loader for that.

As this isn't too related to this template, I'll go ahead and close this ticket.  Thanks for the help!
