### ISSUE TITLE
Query: How to stop that server which is running in port 8080 with the help of Gradle or any other option?

### ISSUE THREAD

**Issue by siva2sachin** [borysn/spring-boot-angular2#4]
After initiating Gradle bootrun, the server is started and able to see the results in localhost. But I'm not able to stop the server which is running in prot 8080. Could you please help me in this.

**Comment by borysn** [comment]
@siva2sachin that's strange, you should have had to start the server from a console, in which case you could do something like `<ctrl> + d` in order to end the current running thread. If you're on a linux box, you could execute `ps aux | grep java`, and kill any running threads. On windows you could use your task manager to locate and end the server. A good restart I'm sure will get it done as well. Does that solve your issue?

If not, I could try to assist you better if you let me know more about your dev environment, and how you started the server.

**Comment by borysn** [comment]
@siva2sachin it should also be noted that the angular2 js code will continue to run, even if the backend java server is stopped. This would lead to not being able to see the json message when navigating to `http://localhost:8080/#/hello`, but if you exit the window and try to return, you will see an appropriate `ERR_CONNECTION_REFUSED` message.

**Comment by siva2sachin** [comment]
Thanks borysn for your help. I just followed your instructions which you mentioned in the code page. Below are my environment setup:
1. Running machine : Windows 7
2. Using Command Prompt to running all the builds and run. And those are as follows,
 gradle clean build
gradle npminstall
 gradle gulp_build
 gradle bootRun
using browser, navigate to localhost:8080.

After that I modify in that code, with gradle gulp_watch, but it's not working. So that's why I planning to stop the server and start it again.

Can you please let me know , is there any console for this. Where I can access it.

**Comment by siva2sachin** [comment]
Thanks for you help!!. I resolved that issue with STS tool. I have a problem with bootstrap css. when I add below code to html, it's displaying as simple text instead of bootstrapped css in the outpage. 

<div class="row">
  <div class="span9">
    Level 1 column
    <div class="row">
      <div class="span6">Level 2</div>
      <div class="span3">Level 2</div>
    </div>
  </div>
</div> 

Do i need to add anything more for bootstrap stuff?

**Comment by borysn** [comment]
@siva2sachin I did not package bootstrap with the starter kit, you will have to add the dependencies yourself. There are so many different front-end libraries, it makes sense to add those when you need them. Here's a general guide for adding front-end dependencies.

1. update `src/main/package.json`
    - add necessary bootstrap dependencies
1. update `src/main/gulpfile.js`
    - add entry to copy dependencies to static
1. update `src/main/index.html`
    - add links to external css/js

**Comment by siva2sachin** [comment]
Thanks. I included and it works fine.

**Comment by siva2sachin** [comment]
I'm trying to connect to Informix JDBC. I have added the dependency(org.springframework.boot:spring-boot-starter-jdbc) to build.gradle file and trying to build it again. When I do "gradle clean build", I'm getting bellow error messages. Can you please correct me what i'm doing wrong here.


![image](https://cloud.githubusercontent.com/assets/10898928/14707848/7a604b4c-07e4-11e6-9ba1-553280413095.png)



![error_jdbc](https://cloud.githubusercontent.com/assets/10898928/14707672/797d70ca-07e3-11e6-8aa2-a603db70e148.jpg)

Can you please help me how to setup informix JDBC connection from this Spring framework?  

Advance Thanks for your help and effort!!

**Comment by borysn** [comment]
@siva2sachin adding a jdbc connection is a little out of scope here for me. I recommend following a [mkyong tutorial](http://www.mkyong.com/spring/maven-spring-jdbc-example/), or searching around for something which suites your needs. Feel free to take a look at another spring project I have going as well. [RVEP](https://gitlab.com/borysn/RVEP/tree/dev) and the [wiki-entry](https://gitlab.com/borysn/RVEP/wikis/page-hts-db)

**Comment by borysn** [comment]
@siva2sachin if you no longer have issues regarding the original query, I would like to go ahead and close up this ticket.

**Comment by siva2sachin** [comment]
Thanks for your help. I will take a look on that. 

Sure :) please close this query as the original issue got resolved for me.
